# Generated by Django 5.2.15 on 2026-08-13 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_bookings_job_custome_idx_bookings_jo_custome_3c5273_idx_and_more'),
        ('payments', '0003_payoutrequest_and_worker_payout_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_9155a4_idx',
            old_name='payments_pa_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_job_id_40caff_idx',
            old_name='payments_pa_job_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutrequest',
            new_name='payments_pa_worker__3c73bd_idx',
            old_name='payments_payoutrequest_worker_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutrequest',
            new_name='payments_pa_status_6374b8_idx',
            old_name='payments_payoutrequest_status_created_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='commission_calculated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='When payment was verified/confirmed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount customer pays (e.g., 1500)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('BKash', 'BKash'), ('Nagad', 'Nagad'), ('Mobile Banking', 'Mobile Banking'), ('Card', 'Card'), ('Digital Wallet', 'Digital Wallet')], default='BKash', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending - Awaiting Verification'), ('Verified', 'Verified - Payment Confirmed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission - automatically calculated (e.g., 150 for 10%)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Receipt/proof of payment', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment gateway or manual entry', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='worker_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Worker earnings - automatically calculated (e.g., 1350 for remaining)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for approval/rejection'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin (may differ from requested)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='payout_account_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='payout_method',
            field=models.CharField(choices=[('Bank Account', 'Bank Account'), ('BKash', 'BKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount worker is requesting to withdraw', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested - Pending Review'), ('Approved', 'Approved - Processing'), ('Processed', 'Processed - Money Sent'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled by Worker')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['worker_payout_status'], name='payments_pa_worker__2ed19c_idx'),
        ),
    ]
