# Generated by Django 5.2.15 on 2026-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_payments_pa_payment_idx_payments_pa_payment_9155a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Raw response from payment gateway API', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_status',
            field=models.CharField(blank=True, help_text='Status returned by payment gateway', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_method',
            field=models.CharField(choices=[('Manual', 'Manual Verification by Admin'), ('Gateway', 'Automatic Gateway Verification'), ('Receipt', 'Receipt/Screenshot Verification')], default='Manual', help_text='How this payment was verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount customer pays (e.g., 1500)', max_digits=10),
        ),
    ]
