# Generated by Django 5.2.15 on 2026-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_gateway_response_payment_gateway_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response from payment gateway'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_status',
            field=models.CharField(blank=True, default='', help_text='Status returned by payment gateway', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission - automatically calculated', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verification_method',
            field=models.CharField(choices=[('Manual', 'Manual - Admin Verified'), ('Gateway', 'Gateway - API Verified'), ('Receipt', 'Receipt - Uploaded Proof')], default='Manual', help_text='How the payment was verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='worker_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Worker earnings after platform commission', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin', max_digits=12, null=True),
        ),
    ]
