# Generated by Django 6.0.5 on 2026-09-04 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage used for this payment', max_digits=5, null=True),
        ),
    ]
