# Generated by Django 5.2.15 on 2026-08-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteService',
        ),
    ]
