# Generated by Django 5.2.15 on 2026-08-18 10:32

from django.db import migrations


def create_categories(apps, schema_editor):
    """Create Category objects from existing Service category strings."""
    Service = apps.get_model('services', 'Service')
    Category = apps.get_model('services', 'Category')
    
    # Get all unique category strings from existing services
    unique_categories = set()
    for service in Service.objects.all():
        if service.category:
            unique_categories.add(service.category)
    
    # Create Category objects for each unique category
    for cat_name in sorted(unique_categories):
        Category.objects.get_or_create(name=cat_name)


def reverse_create_categories(apps, schema_editor):
    """Reverse - delete categories created by this migration."""
    Category = apps.get_model('services', 'Category')
    # Delete categories that were created from service names
    Service = apps.get_model('services', 'Service')
    unique_categories = set()
    for service in Service.objects.all():
        if service.category:
            unique_categories.add(service.category)
    Category.objects.filter(name__in=list(unique_categories)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_favoriteservice'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_create_categories),
    ]
