# Generated by Django 5.2.15 on 2026-08-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_favoriteservice'),
    ]

    operations = [
        # Step 1: Create categories from existing category values
        migrations.RunSQL(
            sql="""
            INSERT INTO services_category (name, description, icon, image, is_active, created_at, updated_at)
            SELECT DISTINCT category, '', '', NULL, 1, datetime('now'), datetime('now')
            FROM services_service
            WHERE category IS NOT NULL AND category != ''
            AND NOT EXISTS (
                SELECT 1 FROM services_category WHERE services_category.name = services_service.category
            );
            """,
            reverse_sql="DELETE FROM services_category WHERE id IN (SELECT DISTINCT sc.id FROM services_category sc JOIN services_service ss ON sc.name = ss.category);",
        ),
        
        # Step 2: Add category_id column
        migrations.AddField(
            model_name='service',
            name='category_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        
        # Step 3: Populate category_id from category names
        migrations.RunSQL(
            sql="""
            UPDATE services_service
            SET category_id = (
                SELECT id FROM services_category
                WHERE services_category.name = services_service.category
            )
            WHERE category IS NOT NULL;
            """,
            reverse_sql="UPDATE services_service SET category_id = NULL;",
        ),
        
        # Step 4: Remove the old category CharField
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        
        # Step 5: Rename category_id to category and make it a proper FK
        migrations.RenameField(
            model_name='service',
            old_name='category_id',
            new_name='category',
        ),
        
        # Step 6: Alter the category field to be a proper ForeignKey
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='services',
                to='services.category',
                help_text='The category this service belongs to'
            ),
        ),
        
        # Step 7: Update model options and add index
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__name', 'name']},
        ),
        
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_available'], name='services_se_categor_0003d9_idx'),
        ),
        
        # Step 8: Alter duration field (if needed from original migration)
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=50, help_text='Estimated duration (e.g., "2 hours")'),
        ),
    ]
