# Generated by Django 5.2.15 on 2026-08-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_create_categories_from_services'),
    ]

    operations = [
    ]
