# Generated by Django 5.2.15 on 2026-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_contact_method',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
