# Generated by Django 5.2.15 on 2026-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_preferred_contact_method_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified_worker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', help_text='Status for customer accounts only', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='worker_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='PENDING', help_text='Status for worker accounts only', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'created_at'], name='accounts_cu_role_ab5ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_blocked'], name='accounts_cu_is_bloc_b09b58_idx'),
        ),
    ]
