# Generated by Django 5.2.15 on 2026-08-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_phase2_workflow_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='bookings_jo_custome_3c5273_idx',
            old_name='bookings_job_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='bookings_jo_worker__94113f_idx',
            old_name='bookings_job_worker_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='bookings_jo_schedul_2790b8_idx',
            old_name='bookings_job_schedul_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='bookings_jo_service_775949_idx',
            old_name='bookings_jo_service_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='bookings_jo_worker__f11e89_idx',
            old_name='bookings_jo_worker_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='bookings_se_custome_4c5aeb_idx',
            old_name='bookings_se_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='bookings_se_status_318213_idx',
            old_name='bookings_se_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='bookings_se_preferr_429b0f_idx',
            old_name='bookings_se_preferr_idx',
        ),
    ]
