# Generated by Django 5.2.15 on 2026-08-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_job_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Considering the job'), ('REJECTED', 'Rejected - Cannot do this job'), ('ACCEPTED', 'Accepted - Ready to work'), ('IN_PROGRESS', 'In Progress - Working on it'), ('COMPLETED', 'Completed - Job finished')], default='PENDING', max_length=20)),
                ('message', models.TextField(help_text='Your response message to the customer')),
                ('customer_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_responses', to='bookings.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'worker'], name='bookings_wo_booking_ff1181_idx'), models.Index(fields=['status'], name='bookings_wo_status_4020e4_idx')],
            },
        ),
    ]
