# Generated by Django 5.2.15 on 2026-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_jobapplication_agreed_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional photo or document', null=True, upload_to='message_attachments/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='problem_photo',
            field=models.ImageField(blank=True, help_text='Optional photo showing the problem', null=True, upload_to='service_request_photos/'),
        ),
    ]
