# Generated by Django 5.2.15 on 2026-08-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_problem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='proposal_message',
            field=models.TextField(blank=True, help_text="Optional message explaining why you're the best choice for this job"),
        ),
    ]
