# Generated by Django 6.1 on 2026-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_job_price_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current negotiated price for the service.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer proposal before the price is agreed.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
