# Generated by Django 6.1 on 2026-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_actual_price_booking_price_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('BOOK_THIS_SERVICE', 'Book This Service'), ('HIRE_ME', 'Hire Me')], default='BOOK_THIS_SERVICE', help_text='How the customer created this booking: Book This Service or Hire Me.', max_length=30),
        ),
    ]
