# Generated by Django 5.2.15 on 2026-08-18 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0006_migrate_category_to_fk_comprehensive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(help_text='Primary profession, e.g. Electrician (Required)', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('service_area', models.CharField(blank=True, max_length=150, null=True)),
                ('nid_number', models.CharField(blank=True, help_text='National ID number', max_length=30, null=True)),
                ('languages', models.CharField(blank=True, max_length=150, null=True)),
                ('id_verification_document', models.FileField(blank=True, null=True, upload_to='worker_documents/')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('response_time', models.CharField(default='Within 24 hours', max_length=50)),
                ('default_preferred_contact', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('SMS', 'SMS')], default='Email', max_length=20)),
                ('payout_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('training_status', models.CharField(choices=[('Pending', 'Pending'), ('In Training', 'In Training'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('average_rating_cached', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Earnings from completed but unpaid jobs', max_digits=12)),
                ('available_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Earnings available for withdrawal after payment is confirmed', max_digits=12)),
                ('withdrawn_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Total amount withdrawn by worker', max_digits=12)),
                ('payout_method', models.CharField(blank=True, choices=[('Bank Account', 'Bank Account'), ('BKash', 'BKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], default='Bank Account', max_length=50)),
                ('payout_account_holder', models.CharField(blank=True, max_length=255)),
                ('payout_account_number', models.CharField(blank=True, max_length=255)),
                ('payout_bank_name', models.CharField(blank=True, max_length=255)),
                ('payout_branch', models.CharField(blank=True, max_length=255)),
                ('bkash_number', models.CharField(blank=True, default='', help_text='bKash phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=20)),
                ('nagad_number', models.CharField(blank=True, default='', help_text='Nagad phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=20)),
                ('rocket_number', models.CharField(blank=True, default='', help_text='Rocket phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='workers', to='services.category')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='services.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
