# Generated by Django 5.2.15 on 2026-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile_bio_workerprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='id_verification_document',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='payout_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='response_time',
            field=models.CharField(default='Within 24 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='service_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
