# Generated by Django 5.2.15 on 2026-07-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_favoriteservice'),
        ('workers', '0003_workerprofile_id_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='services.service'),
        ),
    ]
