# Generated by Django 5.2.15 on 2026-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category'),
        ('workers', '0004_workerprofile_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='average_rating_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='workers', to='services.category'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='completed_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='default_preferred_contact',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('SMS', 'SMS')], default='Email', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
