# Generated by Django 5.2.15 on 2026-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_workerprofile_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='bkash_number',
            field=models.CharField(blank=True, help_text='bKash phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='nagad_number',
            field=models.CharField(blank=True, help_text='Nagad phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='rocket_number',
            field=models.CharField(blank=True, help_text='Rocket phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=15, null=True),
        ),
    ]
