# Generated by Django 5.2.15 on 2026-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_workerprofile_bkash_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='bkash_number',
            field=models.CharField(blank=True, default='', help_text='bKash phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='nagad_number',
            field=models.CharField(blank=True, default='', help_text='Nagad phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='rocket_number',
            field=models.CharField(blank=True, default='', help_text='Rocket phone number for receiving payments (e.g., 01XXXXXXXXX)', max_length=20),
        ),
    ]
