# Generated by Django 5.2.15 on 2026-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_workerprofile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='profession',
            field=models.CharField(help_text='Primary profession, e.g. Electrician (Required)', max_length=100),
        ),
    ]
