# Generated by Django 5.2.15 on 2026-08-13 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_rename_bookings_job_custome_idx_bookings_jo_custome_3c5273_idx_and_more'),
        ('payments', '0004_rename_payments_pa_payment_idx_payments_pa_payment_9155a4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('JOB_COMPLETED', 'Job Completed by Worker'), ('JOB_PAYMENT_SUBMITTED', 'Payment Submitted for Job'), ('PAYMENT_VERIFIED', 'Payment Verified - You Received Payment'), ('PAYMENT_PENDING', 'Payment Pending Verification'), ('JOB_STARTED', 'Job Started'), ('JOB_CANCELLED', 'Job Cancelled'), ('WORKER_APPLIED', 'Worker Applied for Your Request'), ('APPLICATION_ACCEPTED', 'Your Application Was Accepted'), ('APPLICATION_REJECTED', 'Your Application Was Rejected'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.job')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.payment')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_about_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
