# Generated by Django 5.2.15 on 2026-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('JOB_COMPLETED', 'Job Completed by Worker'), ('JOB_STARTED', 'Job Started'), ('JOB_CANCELLED', 'Job Cancelled'), ('JOB_WORKER_UNAVAILABLE', 'Worker Unavailable at Requested Time'), ('JOB_CONFLICT', 'Job Time Conflict'), ('WORKER_APPLIED', 'Worker Applied for Your Request'), ('APPLICATION_ACCEPTED', 'Your Application Was Accepted'), ('APPLICATION_REJECTED', 'Your Application Was Rejected'), ('JOB_PAYMENT_SUBMITTED', 'Payment Submitted for Job'), ('PAYMENT_VERIFIED', 'Payment Verified - You Received Payment'), ('PAYMENT_PENDING', 'Payment Pending Verification'), ('WORKER_APPROVED', 'Your Worker Account Has Been Approved'), ('WORKER_REJECTED', 'Your Worker Account Application Was Rejected'), ('WORKER_PROFILE_UPDATED', 'Your Worker Profile Was Updated'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50),
        ),
    ]
